version: '3.9'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ".env"

  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    restart: always

    env_file:
      - ".env"
